### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp_name_ is not defined

### ISSUE THREAD

**Issue by jamninetyfive** [YuraDev/vue-chrome-extension-template#5]
Uncaught ReferenceError: webpackJsonp_name_ is not defined

i think the vendor.js not  in html

**Comment by tldrjumps** [comment]
Workaround:
- Remove first one of the commonsChunkPlugin will work on webpack.prod.js
I suspect the same, it might be the WebPack.js must be chunk into specific .js, Sorry zero knowledge about how WebPack work.

**Comment by ALiangLiang** [comment]
Have same problem. It's fine in dev script but it happens in build script.

**Comment by yaadyaad** [comment]
The fix of ALiangLiang works fine. Thanks a lot!

**Comment by kkinder** [comment]
Adding those to the content/popup files works for them, but not for the injected js.

**Comment by austince** [comment]
Here are some good resources I've found but haven't quite figured out yet: 
https://github.com/szrenwei/inline-manifest-webpack-plugin/tree/v3.0.1  
https://github.com/webpack/webpack/issues/959  
https://github.com/jantimon/html-webpack-plugin/issues/143  
https://github.com/webpack/webpack/issues/368

**Comment by hkd987** [comment]
@ALiangLiang  where exactly are you injecting the script tags? Think we could make this clear for future people looking to solve this issue.

**Comment by wilderchen** [comment]
> Adding those to the content/popup files works for them, but not for the injected js.

Do you have any idea to make it work for the injected js?

**Comment by eoinoc** [comment]
The fix is here:

https://github.com/YuraDev/vue-chrome-extension-template/issues/16#issuecomment-423745665

Edit `webpack.base.js` 

From:

```javascript
plugins: [
  htmlPage('popup', 'popup', ['popup']),  
  htmlPage('background', 'background', ['background']),  
  ...  
]
```

To:
```javascript
plugins: [
  htmlPage('popup', 'popup', ['manifest', 'vendor', 'popup']),  
  htmlPage('background', 'background', ['manifest', 'vendor', 'background']),  
  ...  
]
```

**Comment by hkd987** [comment]
https://github.com/YuraDev/vue-chrome-extension-template/pull/21


I went ahead and submitted this for a pull 

edit: I see that it probably will not be published since this repo seems to no longer be maintained.

**Comment by HaoweiCh** [comment]
No clue for inject.js?

**Comment by kevinpiac** [comment]
Hey guys, @HaoweiCh, 

A workaround for inject.js I found is to comment/remove CommonChunkPlugin from webpack.prod file.

```js
/// ............ webpack.prod.js
  new ExtractTextPlugin({
      filename: 'css/[name].[contenthash].css'
    }),
    new webpack.HashedModuleIdsPlugin(),
    // 
    // new webpack.optimize.CommonsChunkPlugin({
    //   name: 'vendor',
    //   minChunks: function (module) {
    //     return (
    //       module.resource &&
    //       /\.js$/.test(module.resource) &&
    //       module.resource.indexOf(
    //         path.join(__dirname, '../node_modules')
    //       ) === 0
    //     )
    //   }
    // }),
    // new webpack.optimize.CommonsChunkPlugin({
    //   name: 'manifest',
    //   chunks: ['vendor']
    // })
```

The reason is explained here: https://github.com/webpack/webpack/issues/368

Note: commenting/removing might not be the perfect solution but it works for me without causing an issue.

**Comment by operari** [comment]
Мда если русский берется - то никогда до конца, до ума дело не доведет. Мне уже надоело мучаться со всеми возникшими проблемами. Расширение готово, но не работает из-за кривой сборки. Спасибо!

**Comment by IgorBasov** [comment]
> Мда если русский берется - то никогда до конца, до ума дело не доведет. Мне уже надоело мучаться со всеми возникшими проблемами. Расширение готово, но не работает из-за кривой сборки. Спасибо!

Держите себя в руках, сударь. Вам здесь никто и ничего не должен!
А Ваши суждения попахивают шовинизмом, а потому недостойны нормального человека.
Извинитесь!

**Comment by operari** [comment]
> Держите себя в руках, сударь. Вам здесь никто и ничего не должен!
> А Ваши суждения попахивают шовинизмом, а потому недостойны нормального человека.
> Извинитесь!

Извините)))

**Comment by operari** [comment]
@IgorBasov,

Если серьезно. Вы упрекаете меня в шовинизме, хотя делите людей на достойных и не достойных.
Вы говорите что никто никому ничего не должен, хотя просите, чтобы я за что-то извинился.
Извинился за Ваши суждения отклонёнными когнитивными искажениями.
Мои же суждения - это обычная реакция экспрессиониста.

**Comment by operari** [comment]
@IgorBasov 

Если серьезно. Вы упрекаете меня в шовинизме, хотя делите людей на достойных и недостойных.
Вы говорите что никто никому ничего не должен, хотя просите, чтобы я за что-то извинился.
Извинился за Ваши суждения отклонёнными когнитивными искажениями.
Мои же суждения - это обычная реакция экспрессиониста.
